name: Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [14.x, 16.x, 18.x, 20.x]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: npm run lint
      
    - name: Run tests
      run: npm test
      
    - name: Build project
      run: npm run build
      
    - name: Test CLI basic functionality
      run: |
        node src/index.js --version
        node src/index.js --help
        
    - name: Test CLI commands (Unix)
      if: runner.os != 'Windows'
      run: |
        # 创建测试 git 仓库
        git config --global user.email "test@example.com"
        git config --global user.name "Test User"
        mkdir test-repo && cd test-repo
        git init
        echo "test" > test.txt
        git add . && git commit -m "Initial commit"
        
        # 创建测试分支
        git checkout -b feature/test
        git checkout -b hotfix/test
        git checkout master
        
        # 测试预览功能
        node ../src/index.js preview --patterns "feature/*" --local
        node ../src/index.js preview --patterns "*fix*" --local
        
    - name: Test package contents
      run: npm pack --dry-run